# Problem 1
Sharing and executing the official tutorial model

### NOTE
Here we have tensorflow quick start from [Link](https://www.tensorflow.org/tutorials/quickstart/beginner)

In [1]:
import tensorflow as tf

## Data

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Model

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Untrained Model

### Logits

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.11807608, -0.58446366,  0.73557985, -0.5851472 ,  0.63825   ,
         0.0862681 ,  0.12318598,  0.04069217, -0.42953527, -0.27691874]],
      dtype=float32)

### Probability
through softmax

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10332404, 0.05117905, 0.1915931 , 0.05114408, 0.17382412,
        0.10008923, 0.10385337, 0.09562995, 0.05975535, 0.0696077 ]],
      dtype=float32)

## Loss

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

## Compile and Fit

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3036 - accuracy: 0.9121
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1480 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1100 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0873 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0756 - accuracy: 0.9762


## Evaluation

In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0743 - accuracy: 0.9784


[0.07426247745752335, 0.9783999919891357]

## Another model for usage with probability output

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.89805746e-07, 1.59709035e-09, 2.02054412e-06, 7.97639586e-05,
        1.11920898e-11, 1.58329403e-08, 1.90385329e-11, 9.99914885e-01,
        1.70092846e-08, 3.02612284e-06],
       [7.18595805e-09, 8.47097370e-04, 9.98955131e-01, 1.95559420e-04,
        5.00176386e-15, 1.80916345e-06, 4.01551006e-07, 1.83877690e-14,
        3.56591627e-08, 1.07248941e-11],
       [1.22523386e-06, 9.99528289e-01, 1.50788444e-04, 5.21542688e-06,
        2.56400108e-05, 3.16054206e-06, 1.21444473e-05, 2.31448852e-04,
        2.89822638e-05, 1.31330562e-05],
       [9.99495745e-01, 8.54543325e-10, 2.12497165e-04, 1.66068190e-07,
        2.56820243e-07, 2.31403433e-07, 4.41116345e-06, 1.88224510e-06,
        6.00619927e-08, 2.84865877e-04],
       [6.90587376e-06, 1.07401921e-09, 1.73279750e-06, 1.47738435e-08,
        9.93931532e-01, 4.40748451e-08, 1.48639947e-06, 4.00216632e-05,
        2.65872529e-07, 6.01808494e-03]], dtype=float32)>

# And We done for problem 1 - tensorflow tutorial