# Introduction
Although we have not mentioned them in the previous assignments, classes such as StandardScaler and LinearRegression are available in programming languages like Python.​​


The class syntax is a basic tool for programming using a concept called object orientation.


In this assignment, we will use the classes that have already appeared so far as examples to see and learn what we can do with them. In the second half of the assignment, you will create your ownStandardScaler class from scratch.

In [1]:
# predefines and imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Problem 1
## Enumeration of classes used so far

### Here are classes that i remember so far
- Classifiers/Regressor classes from sklearn (LinearRegression, StandardScaler,...)
- DataFrame, Series from pandas
- Figure, Axis From matplotlib
- numpy.ndarray from numpy

# Problem 2
## Enumeration of methods and instance variables used so far

### Instances and methods used so far:
- np.array() -> sum(), describe(), isna(), count_values()
- DataFrame() -> head(), tail(), array_subscript[]
- axis instance -> plot(), set_title(), scatter(),...
- classifier instance -> fit(), predict()
- list instance ->  append(), remove(), get()

# Problem 3
##  Creating a standardized class by scratch

In [33]:
class ScratchStandardScaler():
    """
    ScratchStandardScaler

    Attributes
    ----------
    mean_ : array of mean for each dimensions, shape(n_features,)

    var_ : array of variance for each dimensions, shape(n_features,)
        
    """
    def fit(self, X: np.array):
        """
        'Fit to the data and calculate mean, var"
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        """
        self.mean_ = X.mean(axis = 0)
        self.var_ = X.var(axis = 0)
    def transform(self, X):
        """
        return scaled x according to mean and var
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
            
        Returns
        ----------
        X_scaled : ndarray, shape (n_samples, n_features)
        """
        return (X - self.mean_) / self.var_**(1/2)

X = np.array([range(1,5), range(2,6), range(6,10)])
scaler = ScratchStandardScaler()
scaler.fit(X)
display('Data',X,'Means:',scaler.mean_,'Variances', scaler.var_)
display('Scaled Data: ',scaler.transform(X))

'Data'

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

'Means:'

array([3., 4., 5., 6.])

'Variances'

array([4.66666667, 4.66666667, 4.66666667, 4.66666667])

'Scaled Data: '

array([[-0.9258201 , -0.9258201 , -0.9258201 , -0.9258201 ],
       [-0.46291005, -0.46291005, -0.46291005, -0.46291005],
       [ 1.38873015,  1.38873015,  1.38873015,  1.38873015]])

### Test upon given test code

In [34]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# Problem 4
## Creating a class that performs 4 arithmetic operations

In [35]:
class ExampleClass():

    def __init__(self, value):
        value_type = type(value)
        if value_type is float or value_type is int:
            self.value = value
        else:
            raise TypeError('Value must be numeric!')
    def add(self, value2):
        self.value += value2
    def subtract(self,value2):
        self.value -= value2
    def multiply(self,value2):
        self.value *= value2
    def divide(self,value2):
        self.value /= value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(2)
print("value : {}".format(example.value))
example.multiply(5)
print("value : {}".format(example.value))
example.divide(10)
print("value : {}".format(example.value))


value : 5
value : 8
value : 6
value : 30
value : 3.0
