# Introduction
Consider the following matrices A and B.

$ A = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix} $ 
And $
B = \begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix} $

When expressed in NumPy, it becomes as follows.

```
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```

In [31]:
#predefines and imports
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Problem 1
## Hand calculation of matrix multiplication

### Manual solution for $A \cdot B$: 
So matrix multiplication is essentially the dot product of each pairs of row from matrix A and column from matrix B, organized according to their position in to the matrix $C = A \cdot B$

We go one by one for each pair, starting at row 0, column 0:
- (0,0): $[-1,2,3] \cdot [0,0,2] = 6$
- (0,1): $[-1,2,3] \cdot [2,2,9] = 29$
- (0,2): $[-1,2,3] \cdot [1,-8,-1] = -20$
- (0,0): $[4,-5,6] \cdot [0,0,2] = 12$
- (0,1): $[4,-5,6] \cdot [2,2,9] = 52$
- (0,2): $[4,-5,6] \cdot [1,-8,-1] = 38$
- (0,0): $[7,8,-9] \cdot [0,0,2] = -18$
- (0,1): $[7,8,-9] \cdot [2,2,9] = -51$
- (0,2): $[7,8,-9] \cdot [1,-8,-1] = -48$

Then we can arrange the results into a matrix to get the final result:

$A\cdot B = \begin{bmatrix}
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}$



# Problem 2
## Numpy matrix multiplication

In [32]:
def problem2():
    print(a_ndarray@b_ndarray)
problem2()

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### NOTE:
- can use matmul (same as @) or dot to calculate 2d matrix
- dot is dot product, not same as others for higher dimensions

# Problem 3
## One element of matrix multiplication
""dot product""

In [33]:
def dot(X,Y): #of 2 vectors only
    dot_prod = 0
    for x,y in zip(X,Y):
        dot_prod += x*y
    # print(dot_prod)
    return dot_prod
def problem3():
    first_dot = dot(a_ndarray[0,:], b_ndarray[:,0])
    print("Element (0,0) of A.B: ",first_dot)
problem3()

Element (0,0) of A.B:  6


# Problem 4
## Matrix Product

In [34]:
def product(A,B):
    if A.shape[0] != B.shape[1]:
        print('Dimension mismatched, cant perform production!')
        return None
    matrix = []
    for i in range(A.shape[0]):
        row = []
        for j in range(B.shape[1]):
            row.append(dot(A[i,:], B[:,j]))
        matrix.append(row)
    return np.array(matrix)
def problem4():
    print("A.B = ", product(a_ndarray,b_ndarray))

problem4()

A.B =  [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### NOTE: problem 4
- Looking at the above problem, a question hit me and i cant seems to see the answer on the internet. So, Can we use numpy array ** instead ** of conventional python list, **completely**? 

- I mean sure, the normal list is not faster and is not the right way to work with matrixes (which is what numpy is made for). But the way i did problem 4 made me think that the simple manipulation of python list makes it the superior contender for list or vector specific task, **ilterative tasks**. Where it would be more cumbersome to work with np.array due to dimension restrictions!
- ** What do you think? **

# Problem 5
## Fixing mismatched product inputs

### The function in problem 4 is modified to check for dimensions

In [35]:
def problem5():
    d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
    e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
    result = product(d_ndarray, e_ndarray)
    print(result)
problem5()

Dimension mismatched, cant perform production!
None


# Problem 6
## Transpose

In [36]:
def problem6():
    print('A: ', a_ndarray)
    print('A transpose: ', a_ndarray.T)
problem6()

A:  [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
A transpose:  [[-1  4  7]
 [ 2 -5  8]
 [ 3  6 -9]]
